- name: check cluster
  azure.azcollection.azure_rm_openshiftmanagedcluster_info:
    resource_group: "{{ aro_resource_group }}"
    name: "{{ aro_cluster_name }}"
  register: _aro_exists
  no_log: true

- block:
    - name: check cluster
      azure.azcollection.azure_rm_openshiftmanagedcluster_info:
        resource_group: "{{ aro_resource_group }}"
        name: "{{ aro_cluster_name }}"
      register: _aro_check
      until: _aro_check.clusters == {}
      retries: 120
      delay: 60
      failed_when: false
      changed_when: false
      no_log: true
      when: _aro_exists.clusters.properties.provisioningState == "Deleting"

    - name: Destroy aro cluster
      azure.azcollection.azure_rm_openshiftmanagedcluster:
        resource_group: "{{ aro_resource_group }}"
        name: "{{ aro_cluster_name }}"
        location: "{{ aro_location }}"
        state: absent
      when: _aro_exists.clusters.properties.provisioningState != "Deleting"
  when: _aro_exists.clusters != {}
