---
# tasks file for roles/keyvault-secret
- block:
    - name: Get Key Vault by name
      azure_rm_keyvault_info:
        resource_group: "{{ keyvault_resource_group }}"
        name: "{{ keyvault_vault_name }}"
      register: _keyvault
      no_log: true

    - name: Set key vault URI fact
      set_fact:
        keyvault_vault_uri: "{{ _keyvault['keyvaults'][0]['vault_uri'] }}"
  when: keyvault_vault_uri is undefined

- set_fact:
    _secret_generator: "/dev/null {{ keyvault_secret_constraints }}"

- set_fact:
    _keyvault_secret_value:  "{{ keyvault_secret_value }}"
  when:
    - (keyvault_secret_value is defined) and
      (keyvault_secret_value != "")
  no_log: true
- set_fact:
    _keyvault_secret_value: "{{ lookup('ansible.builtin.password', _secret_generator) }}"
  when:
    - (keyvault_secret_value == "") or
      (keyvault_secret_value is undefined)
  no_log: true

- name: "check if secret {{ keyvault_secret_name }} exists"
  azure.azcollection.azure_rm_keyvaultsecret_info:
    vault_uri: "{{ keyvault_vault_uri }}"
    name: "{{ keyvault_secret_name }}"
  register: _keyvault_secret_info
  no_log: true

- block:
    - name: create secret for {{ keyvault_secret_name }}
      azure_rm_keyvaultsecret:
        secret_name: "{{ keyvault_secret_name }}"
        secret_value: "{{ _keyvault_secret_value }}"
        keyvault_uri: "{{ keyvault_vault_uri }}"
    - set_fact:
        output_keyvault_secret_value: "{{ _keyvault_secret_value }}"
      no_log: true
  when: _keyvault_secret_info.secrets | length == 0

# todo resolve conflict when both secrets are set
- set_fact:
    output_keyvault_secret_value: "{{ _keyvault_secret_info.secrets[0].secret }}"
  no_log: true
  when: _keyvault_secret_info.secrets | length == 1

