- name: "provision aro-landing-zone"
  hosts: all
  gather_facts: false
  connection: local
  vars:
    ansible_python_interpreter: ./virtualenv/bin/python
    diag_name: "{{ hub_name }}{{ lookup('community.general.random_string', length=6, special=false, numbers=false) }}"
    cluster_name: "{{ cluster_name_override | default(prefix + '-aro-' + location) }}"
    hub_name: "{{ hub_name_override | default(prefix + '-hub-aro') }}"
    spoke_name: "{{ spoke_name_override | default(prefix + '-spoke-aro') }}"
  roles:
    - role: _pre
    - role: resource_group
      vars:
        rg_hub_name: "{{ hub_name }}-rg"
        rg_spoke_name: "{{ spoke_name }}-rg"
        rg_location: "{{ location }}"
    - role: keyvault
      vars:
        keyvault_name: "{{ hub_name }}-kv"
        keyvault_resource_group: "{{ output_rg_hub_name | default( hub_name + '-rg')  }}"
        keyvault_tenant_id: "{{ azure_tenant_id }}"
        keyvault_subscription_id: "{{ azure_subscription_id }}"
    - role: vnet
      vars:
        vnet_location: "{{ location }}"
        vnet_hub_rg: "{{ output_rg_hub_name | default( hub_name + '-rg')  }}"
        vnet_spoke_rg: "{{ output_rg_spoke_name | default( spoke_name + '-rg') }}"
        vnet_hub_name: "{{ hub_name }}-vnet"
        vnet_spoke_name: "{{ spoke_name }}-vnet"
        vnet_fw_name: "{{ spoke_name }}-fw"
    - role: service-principal
      vars:
        sp_aro_sp_password: "{{ aro_sp_password }}"
        sp_aro_rg: "{{ output_rg_spoke_name | default( spoke_name + '-rg') }}"
        sp_aro_cluster_name: "{{ cluster_name }}"
        sp_aro_vnet_name: "{{ spoke_name }}-vnet"
        sp_subscription_id: "{{ azure_subscription_id }}"
        sp_tenant_id: "{{ azure_tenant_id }}"
    - role: aro
      vars:
        aro_resource_group:  "{{ output_rg_spoke_name | default( spoke_name + '-rg') }}"
        aro_cluster_name: "{{ cluster_name }}"
        aro_vnet_id: "{{ output_vnet_spoke_vnet_id }}"
        aro_location: "{{ location }}"
        aro_control_subnet_id: "{{ output_vnet_control_subnet_id }}"
        aro_worker_subnet_id: "{{ output_vnet_worker_subnet_id }}"
        aro_sp_client_id: "{{ output_sp_app_id }}"
        aro_sp_client_secret: "{{ output_sp_aro_sp_password | default(aro_sp_password) }}"
    - role: bastion
      vars:
        bastion_name: "{{ hub_name }}-bastion"
        bastion_resource_group: "{{ output_rg_hub_name | default( hub_name + '-rg')  }}"
        bastion_subnet_id: "{{ output_vnet_bastion_subnet_id }}"
    - role: jumpbox
      vars:
        jumbox_name: "{{ hub_name }}-jump"
        jumpbox_resource_group: "{{ output_rg_hub_name | default( hub_name + '-rg')  }}"
        jumpbox_subnet_name: "{{ output_vnet_vm_subnet_name }}"
        jumpbox_vnet_name: "{{ hub_name }}-vnet"
    - role: frontdoor
      vars:
        frontdoor_aro_resource_group: "{{ _output_aro_cluster_rg_id | basename }}"
        frontdoor_resource_group: "{{ output_rg_spoke_name | default( spoke_name + '-rg') }}"
        frontdoor_subnet_id: "{{ output_vnet_worker_subnet_id }}"
    - role: finish
      vars:
        aro_cluster_name: "{{ cluster_name }}"
        aro_resource_group:  "{{ output_rg_spoke_name | default( spoke_name + '-rg') }}"
