- include_tasks: wait-for-cluster.yml

- debug:
    msg: |
      ***************************************
      {{ aro_cluster_name }} created.
      Run the following to get login credentials
      ***************************************

      ARO_API=$(az aro show \
      --name {{ aro_cluster_name }} \
      --resource-group {{ aro_resource_group }} \
      -o tsv --query apiserverProfile.url)

      ARO_CONSOLE=$(az aro show \
        --name {{ aro_cluster_name }} \
        --resource-group {{ aro_resource_group }} \
        -o tsv --query consoleProfile)

      ARO_PASS=$(az aro list-credentials \
        --name {{ aro_cluster_name }} \
        --resource-group {{ aro_resource_group }} \
        -o tsv --query kubeadminPassword)

      oc login $ARO_API --username kubeadmin --password "$ARO_PASS"

      echo "Console: $ARO_CONSOLE"
      echo "Username: kubeadmin"
      echo "Password: $ARO_PASS"

    verbosity: 0


# - set_fact:
#     azr_aro_control_subnet_id: "{{ _control_subnet.state.id }}"
#     when: _control_subnet is defined
# - set_fact:
#     azr_aro_machine_subnet_id: "{{ _machine_subnet.state.id }}"
#     when: _machine_subnet is defined

# - name: create service principal
#   command: az ad sp create-for-rbac -n "http://{{ aro_cluster_name }}-ansible-aro4-builds" -o jsonc
#   register: _sp
#   changed_when: false

# # - debug:
# #     msg: "{{ _sp.stdout }}"

# - set_fact:
#     _sp_id: "{{ (_sp.stdout | from_json).appId }}"
#     _sp_secret: "{{ (_sp.stdout | from_json ).password }}"

# - name: Create openshift cluster
#   azure.azcollection.azure_rm_openshiftmanagedcluster:
#     resource_group: "{{ aro_resource_group }}"
#     name: "{{ aro_cluster_name }}"
#     location: "{{ azr_location }}"
#     service_principal_profile:
#       client_id: "{{ _sp_id }}"
#       client_secret: "{{ _sp_secret }}"
#     ingress_profiles:
#       - visibility: "{{ azr_aro_public_ingress  | ternary('Public', 'Private') }}"
#     api_server_profile:
#       visibility: "{{ azr_aro_public_api  | ternary('Public', 'Private') }}"
#     worker_profiles:
#       - vm_size : "Standard_D4s_v3"
#         subnet_id : "{{ azr_aro_control_subnet_id }}"
#         disk_size : 128
#         count : 3
#     master_profile:
#       vm_size : "Standard_D8s_v3"
#       subnet_id: "{{ azr_aro_machine_subnet_id }}"

#     # cluster_profile:
#     #   cluster_resource_group_id: "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/clusterResourceGroup"
#     #   domain: "mydomain"
#     # service_principal_profile:
#     #   client_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#     #   client_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#     # network_profile:
#     #   pod_cidr: "10.128.0.0/14"
#     #   service_cidr: "172.30.0.0/16"
