- block:
  - name: get subscription
    azure.azcollection.azure_rm_subscription_info:
      all: True
    register: _subscription

  - set_fact:
      _azr_subscription_id: "{{ _subscription.subscriptions[0].subscription_id }}"
  - set_fact:
      _azr_tenant_id: "{{ _subscription.subscriptions[0].tenant_id }}"

- set_fact:
    app_display_name: "http://aro-{{ sp_aro_cluster_name }}"
