- include_role:
    name: keyvault-secret
  vars:
    keyvault_secret_name: "{{ sp_keyvault_secret_name }}"
    keyvault_secret_value: "{{ sp_aro_sp_password | default('') }}"
    keyvault_secret_constraints: "chars=ascii_lowercase,ascii_uppercase,digits,punctuation length=12"

- set_fact:
    sp_aro_sp_password: "{{ output_keyvault_secret_value }}"
  no_log: true
