---
# defaults file for roles/keyvault
keyvault_name: keyvault-kv
keyvault_resource_group: keyvault-rg

keyvault_enable_purge_protection: false
keyvault_enable_soft_delete: false

# leave unset to use resource group location
# keyvault_location:

keyvault_tenant_id: ""
keyvault_subscription_id: ""

