- name: Delete the hub resource group
  azure_rm_resourcegroup:
    name: "{{ rg_hub_name }}"
    state: absent
    force_delete_nonempty: yes

- name: Delete the spoke resource group
  azure_rm_resourcegroup:
    name: "{{ rg_spoke_name }}"
    state: absent
    force_delete_nonempty: yes
