- name: Create virtual network peering for hub to spoke
  azure_rm_virtualnetworkpeering:
    resource_group: "{{ vnet_hub_rg }}"
    virtual_network: "{{ vnet_hub_name }}"
    name: "{{ vnet_hub_name }}To{{ vnet_spoke_name }}"
    remote_virtual_network:
      resource_group: "{{ vnet_spoke_rg }}"
      name: "{{ vnet_spoke_name }}"
    allow_forwarded_traffic: true
    # todo - push peer traffic via fw
    allow_virtual_network_access: true

- name: Create virtual network peering for spoke to hub
  azure_rm_virtualnetworkpeering:
    resource_group: "{{ vnet_spoke_rg }}"
    virtual_network: "{{ vnet_spoke_name }}"
    name: "{{ vnet_spoke_name }}To{{ vnet_hub_name }}"
    remote_virtual_network:
      resource_group: "{{ vnet_hub_rg }}"
      name: "{{ vnet_hub_name }}"
    allow_forwarded_traffic: true
    # todo - push peer traffic via fw
    allow_virtual_network_access: true
