---
- name: check if bastion exists
  azure.azcollection.azure_rm_bastionhost_info:
    name: "{{ bastion_name }}"
    resource_group: "{{ bastion_resource_group }}"
  register: _bastion_info

- block:
    - name: Destroy bastion host
      azure.azcollection.azure_rm_bastionhost:
        name: "{{ bastion_name }}"
        resource_group: "{{ bastion_resource_group }}"
        state: absent
      when: _bastion_info.bastion_host[0].provisioning_state != 'Deleting'

    - name: wait for bastion to be deleted
      azure.azcollection.azure_rm_bastionhost_info:
        name: "{{ bastion_name }}"
        resource_group: "{{ bastion_resource_group }}"
      register: _bastion_info
      until: _bastion_info.bastion_host | length == 0
      retries: 120
      delay: 60
  when: _bastion_info.bastion_host | length > 0


- name: Destroy a public ip address
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "{{ bastion_resource_group }}"
    name: "{{ bastion_name }}-pip"
    state: absent
