---
# tasks file for roles/bastion
- name: get subscription
  azure.azcollection.azure_rm_subscription_info:
    all: True
  register: _subscription

- set_fact:
    _azr_subscription_id: "{{ _subscription.subscriptions[0].subscription_id }}"

- name: Create a public ip address
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "{{ bastion_resource_group }}"
    name: "{{ bastion_name }}-pip"
    allocation_method: static
    sku: Standard
  register: _bastion_public_ip

- name: Get public ip ID
  azure_rm_publicipaddress_info:
    resource_group: "{{ bastion_resource_group }}"
    name: "{{ bastion_name }}-pip"
  register: _bastion_public_ip_info

- name: Create bastion host
  azure.azcollection.azure_rm_bastionhost:
    name: "{{ bastion_name }}"
    resource_group: "{{ bastion_resource_group }}"
    ip_configurations:
      - name: config
        subnet:
          id: "{{ bastion_subnet_id }}"
        public_ip_address:
          id: "{{ _bastion_public_ip_info.publicipaddresses[0].id }}"
          # id: "/subscriptions/{{ _azr_subscription_id }}/resourceGroups/{{ bastion_resource_group }}/providers/Microsoft.Network/publicIPAddresses/{{ bastion_name }}-pip"
        private_ip_allocation_method: Dynamic
    sku:
      name: Standard
    enable_tunneling: True
    enable_shareable_link: True
    enable_ip_connect: True
    enable_file_copy: True
    scale_units: 6
    disable_copy_paste: False
