- name: Destroy jumpbox vm
  azure_rm_virtualmachine:
    resource_group: "{{ jumpbox_resource_group }}"
    name: "{{ jumbox_name }}"
    state: absent

- name: Destroy windows jumpbox vm
  azure_rm_virtualmachine:
    resource_group: "{{ jumpbox_resource_group }}"
    name: "jumpbox-win"
    state: absent

- name: Destroy jumpbox nic
  azure_rm_networkinterface:
    name: "{{ jumbox_name }}-win-nic"
    resource_group: "{{ jumpbox_resource_group }}"
    subnet_name: "{{ jumpbox_subnet_name }}"
    virtual_network: "{{ jumpbox_vnet_name }}"
    state: absent
