- include_role:
    name: keyvault-secret
  vars:
    keyvault_secret_name: "{{ jumpbox_keyvault_secret_name }}"
    keyvault_secret_value: "{{ jumpbox_password | default('') }}"
    keyvault_secret_constraints: "chars=ascii_lowercase,ascii_uppercase,digits,punctuation length=8"

- set_fact:
    jumpbox_password: "{{ output_keyvault_secret_value }}"
  no_log: true
