# resource "azurerm_key_vault_secret" "vm_admin_username" {
#   name = "vmadminusername"
#   value = var.vm_admin_username
#   key_vault_id = azurerm_key_vault.kv.id
# }

# resource "azurerm_key_vault_secret" "vm_admin_password" {
#   name = "vmadminpassword"
#   value = var.vm_admin_password
#   key_vault_id = azurerm_key_vault.kv.id
# }

- name: Create a network interface with private IP address only (no Public IP)
  azure_rm_networkinterface:
    name: "{{ jumbox_name }}-win-nic"
    resource_group: "{{ jumpbox_resource_group }}"
    subnet_name: "{{ jumpbox_subnet_name }}"
    virtual_network: "{{ jumpbox_vnet_name }}"
    create_with_security_group: False
    ip_configurations:
      - name: ipconfig1
        primary: True
  register: _jumpbox_win_nic

# - name: Create an availability set for managed disk vm
#   azure_rm_availabilityset:
#     name: "{{ jumbox_name }}-win-os"
#     resource_group: "{{ jumpbox_resource_group }}"
#     platform_update_domain_count: 5
#     platform_fault_domain_count: 2
#     sku: Aligned

- name: Create windows jumpbox vm
  azure_rm_virtualmachine:
    resource_group: "{{ jumpbox_resource_group }}"
    name: "jumpbox-win"
    admin_username: "{{ jumpbox_username }}"
    admin_password: "{{ jumpbox_password }}"
    subnet_name: "{{ jumpbox_subnet_name }}"
    network_interfaces: "{{ jumbox_name }}-win-nic"
    vm_size: Standard_D4s_v3
    os_type: Windows
    os_disk_caching: ReadWrite
    managed_disk_type: Standard_LRS
    image:
      offer: "WindowsServer"
      publisher: "MicrosoftWindowsServer"
      version: "latest"
      sku: "2016-Datacenter"
    custom_data: "{{ lookup('file', 'start_script.ps1') }}"
  register: _jumphost_win

- name: Create VM Extension
  azure_rm_virtualmachineextension:
    name: "jumpbox-win-cfg"
    resource_group: "{{ jumpbox_resource_group }}"
    virtual_machine_name: "jumpbox-win"
    publisher: Microsoft.Compute
    virtual_machine_extension_type: CustomScriptExtension
    type_handler_version: 1.9
    settings: |
      {
        "commandToExecute": "type C:\AzureData\CustomData.bin | powershell -ExecutionPolicy Unrestricted"
      }
  # async: 360
    # publisher: Microsoft.Compute
    # virtual_machine_extension_type: CustomScript
    # type_handler_version: 1.9
    # settings: |
    #    {
    #       "commandToExecute": "powershell -ExecutionPolicy Unrestricted -File start_script.ps1"
    #     }
